# Generated by Django 4.0.6 on 2022-07-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_category_slugs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slugs',
            new_name='slug',
        ),
    ]
